//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionUniversidadC_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_universidadEntities : DbContext
    {
        public gestion_universidadEntities()
            : base("name=gestion_universidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<registro_materia_por_alumno> registro_materia_por_alumno { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<materia> materia { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
    }
}
