//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionUniversidadC_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia()
        {
            this.registro_materia_por_alumno = new HashSet<registro_materia_por_alumno>();
        }
    
        public int id { get; set; }
        public string nombre_materia { get; set; }
        public Nullable<int> horas_cursado { get; set; }
        public string duracion { get; set; }
        public Nullable<int> carrera_id { get; set; }
    
        public virtual carrera carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_materia_por_alumno> registro_materia_por_alumno { get; set; }
    }
}
